services:
  minecraft-server:
    image: ${IMG_NAME}
    container_name: ${CONT_NAME}
    ports:
      - "${SRV_PORT}:25565"
    environment:
      - JVM_XMX=${XMX}
      - JVM_XMS=${XMS}
      - SERVER_JAR=forge_server.jar
    volumes:
      - ${MNT_DIR}:/minecraft
    stdin_open: true
    tty: true
    restart: "no"
    entrypoint: ["/bin/sh", "-c", "/tmp/init.sh"]
    